# Generated by Django 3.0.3 on 2020-03-04 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpRUT', models.IntegerField(max_length=12, null=True)),
                ('EmpRazonSocial', models.CharField(max_length=50, null=True)),
                ('EmpDirCalle', models.CharField(max_length=50, null=True)),
                ('EmpDirEsquina', models.CharField(max_length=30, null=True)),
                ('EmpDirNum', models.CharField(max_length=30, null=True)),
                ('EmpDirEmail', models.CharField(max_length=50, null=True)),
                ('EmpActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='rubros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubroNom', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('EmpId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cuenta.empresas')),
                ('LunesDesde', models.TimeField(null=True)),
                ('LunesHasta', models.TimeField(null=True)),
                ('MartesDesde', models.TimeField(null=True)),
                ('MartesHasta', models.TimeField(null=True)),
                ('MiercolesDesde', models.TimeField(null=True)),
                ('MiercolesHasta', models.TimeField(null=True)),
                ('JuevesDesde', models.TimeField(null=True)),
                ('JuevesHasta', models.TimeField(null=True)),
                ('ViernesDesde', models.TimeField(null=True)),
                ('ViernesHasta', models.TimeField(null=True)),
                ('SabadoDesde', models.TimeField(null=True)),
                ('SabadoHasta', models.TimeField(null=True)),
                ('DomingoDesde', models.TimeField(null=True)),
                ('DomingoHasta', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuariosEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsuEmpRol', models.CharField(choices=[('Admin', 'Admin'), ('Sub-Admin', 'Sub-Admin')], max_length=15, null=True)),
                ('UsuEmpActivo', models.BooleanField(default=True)),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuenta.empresas')),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UsuId', 'EmpId')},
            },
        ),
        migrations.AddField(
            model_name='empresas',
            name='EmpRubro1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EmpRubro1', to='cuenta.rubros'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='EmpRubro2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EmpRubro2', to='cuenta.rubros'),
        ),
        migrations.CreateModel(
            name='solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaSolicitud', models.DateField()),
                ('HorarioSolicitud', models.TimeField()),
                ('SeConcreto', models.BooleanField(default=False)),
                ('ComentarioAdmin', models.CharField(max_length=200, null=True)),
                ('ComentarioUsuario', models.CharField(max_length=200, null=True)),
                ('SolicitudActivo', models.BooleanField(default=True)),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuenta.usuariosEmpresas')),
                ('UsuAdminResponsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UsuAdminResponsable', to='cuenta.usuariosEmpresas')),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UsuId', 'EmpId', 'UsuAdminResponsable')},
            },
        ),
    ]
