# Generated by Django 3.0.3 on 2020-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='EmpRUT',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
