# Generated by Django 3.0.3 on 2020-03-04 04:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuenta', '0002_auto_20200304_0124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='empresas',
            new_name='empresa',
        ),
        migrations.RenameModel(
            old_name='horarios',
            new_name='horario',
        ),
        migrations.RenameModel(
            old_name='rubros',
            new_name='rubro',
        ),
        migrations.RenameModel(
            old_name='solicitudes',
            new_name='solicitud',
        ),
        migrations.RenameModel(
            old_name='usuariosEmpresas',
            new_name='usuariosEmpresa',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='HorarioSolicitud',
            new_name='HoraSolicitud',
        ),
    ]
