# Generated by Django 3.0.3 on 2020-03-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_auto_20200304_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='EmpDirEsquina',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='EmpDirNum',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='EmpRUT',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
