# Generated by Django 3.0.3 on 2020-03-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_auto_20200304_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosempresa',
            name='UsuEmpRol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sub-Admin', 'Sub-Admin')], max_length=15),
        ),
    ]
