# Generated by Django 3.0.3 on 2020-03-04 05:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuenta', '0007_auto_20200304_0149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariosempresa',
            unique_together={('UsuId', 'EmpId', 'UsuEmpRol')},
        ),
    ]
