# Generated by Django 3.0.3 on 2020-03-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_auto_20200304_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='EmpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuenta.empresa'),
        ),
    ]
