# Generated by Django 3.0.3 on 2020-03-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_auto_20200304_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='EmpTelefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
