# Generated by Django 3.0.3 on 2020-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_auto_20200308_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='EmpDescripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='EmpDirEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
